### PR TITLE
Make quotes happy in README

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by staudenmeir** [comment]
What is the benefit of this change?

**Comment by szepeviktor** [comment]
- the whole string is quoted
- there will be no quote in middle of the string

I cannot convince you!

**Comment by staudenmeir** [comment]
I just want to be absolutely sure that it still works on all operating systems. The quotes were necessary in the first place to make it work everywhere.

**Comment by szepeviktor** [comment]
I leave it up to you.
You may run GitHub Actions on Windows etc.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
