### PR TITLE
Cast to bigint on PostgreSQL to avoid issues with big integer IDs

### PR DESCRIPTION
**Pull request by nikazooz**
I've noticed that when a model uses `HasJsonRelationships` if that model or some related model has BIGINT ID, not just as column type but has actual value that is out of range for regular integer, PostgreSQL throws an error saying something like "Numeric value out of range". 

Please let me know what you think about this solution.

Thanks for the great package!
Cheers!

### CODE REVIEW

**Comment by staudenmeir** [comment]
Thanks, I'll take a look.

**Comment by nikazooz** [comment]
Don't know how to fix the issue with sqlsrv...

**Comment by staudenmeir** [comment]
Since it's much easier, I think it's ok to not explicitly test big integers. Can you revert all the changes to tests?

**Comment by nikazooz** [comment]
I've reverted all the changes to tests.

**Comment by staudenmeir** [comment]
Thanks! I've released a new version.

**Comment by nikazooz** [comment]
Great, thank you! 🙂

**Pull request merged**
